foreground = yes
debug = 4

[kerberos]
options = NO_SSLv2
options = NO_SSLv3
options = NO_TLSv1_1
ciphers = ALL:!aNULL:!eNULL:!EXPORT:!LOW
accept = 1443
connect = open-oscar-server:1088
cert = /etc/stunnel/server.pem

[oscar]
options = NO_SSLv2
options = NO_SSLv3
options = NO_TLSv1_1
ciphers = ALL:!aNULL:!eNULL:!EXPORT:!LOW
accept = 15193
connect = open-oscar-server:5190
cert = /etc/stunnel/server.pem
